[package]
authors = ["The Rust Project Developers"]
name = "pal_windows"
version = "0.0.0"

[lib]
name = "pal_windows"
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
alloc = { path = "../liballoc" }
core = { path = "../libcore" }
libc = { path = "../rustc/libc_shim" }
